[tool.poetry]
name = "jace-the-bot"
version = "0.1.0"
description = ""
authors = ["SirCaptainMitch <hamann.mitchell@gmail.com>"]
readme = "README.md"
packages = [{include = "jace_the_bot"}]

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.2.3"
requests = "^2.30.0"
pydantic = "^1.10.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
